#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const skillsRoot = path.join(root, 'skills');
const outputPath = path.join(root, 'docs', 'skills-index.md');
const categoryOrder = [
  'frontend',
  'accessibility',
  'design-systems',
  'testing',
  'documentation',
  'ux'
];
const categoryLabels = {
  'accessibility': 'Accessibility',
  'design-systems': 'Design Systems',
  'documentation': 'Documentation',
  'frontend': 'Frontend',
  'testing': 'Testing',
  'ux': 'UX'
};

function titleFromSlug(slug) {
  return slug.split('-').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
}

function extractSection(content, section) {
  const pattern = new RegExp('^##\\s+' + section + '\\s*\\n+([\\s\\S]*?)(?=^##\\s+|$)', 'm');
  const match = content.match(pattern);
  return match ? match[1].trim() : '';
}

function firstParagraph(markdown) {
  return markdown.split(/\\n\\s*\\n/).map((part) => part.trim()).find(Boolean) || '';
}

const categories = fs.readdirSync(skillsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort((a, b) => {
    const aIndex = categoryOrder.indexOf(a);
    const bIndex = categoryOrder.indexOf(b);

    if (aIndex === -1 && bIndex === -1) {
      return a.localeCompare(b);
    }

    if (aIndex === -1) {
      return 1;
    }

    if (bIndex === -1) {
      return -1;
    }

    return aIndex - bIndex;
  });

const lines = [
  '# Skills Index',
  '',
  'Generated by `npm run index`. Do not edit this file by hand.',
  ''
];

let total = 0;

for (const category of categories) {
  const categoryPath = path.join(skillsRoot, category);
  const skillDirs = fs.readdirSync(categoryPath, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  lines.push('## ' + (categoryLabels[category] || titleFromSlug(category)));
  lines.push('');
  lines.push('| Skill | Description |');
  lines.push('| --- | --- |');

  for (const skillSlug of skillDirs) {
    const skillFile = path.join(categoryPath, skillSlug, 'SKILL.md');
    const content = fs.readFileSync(skillFile, 'utf8');
    const name = firstParagraph(extractSection(content, 'Skill Name')) || titleFromSlug(skillSlug);
    const description = firstParagraph(extractSection(content, 'Description')).replace(/\\n/g, ' ');
    const relPath = path.relative(path.dirname(outputPath), skillFile).replace(/\\/g, '/');
    lines.push('| [' + name + '](' + relPath + ') | ' + description + ' |');
    total += 1;
  }

  lines.push('');
}

lines.push('Total skills: ' + total);
lines.push('');

fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log('Generated ' + path.relative(root, outputPath) + ' with ' + total + ' skills.');
